<!DOCTYPE HTML>
<html lang="en" class="sidebar-visible no-js rust">
    <head>
        <!-- Book generated using mdBook -->
        <meta charset="UTF-8">
        <title>Failures - RAFFIOT Guide</title>
        
        


        <!-- Custom HTML head -->
        


        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff" />

        
        <link rel="icon" href="favicon.svg">
        
        
        <link rel="shortcut icon" href="favicon.png">
        
        <link rel="stylesheet" href="css/variables.css">
        <link rel="stylesheet" href="css/general.css">
        <link rel="stylesheet" href="css/chrome.css">
        
        <link rel="stylesheet" href="css/print.css" media="print">
        

        <!-- Fonts -->
        <link rel="stylesheet" href="FontAwesome/css/font-awesome.css">
        
        <link rel="stylesheet" href="fonts/fonts.css">
        

        <!-- Highlight.js Stylesheets -->
        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">
        <link rel="stylesheet" href="ayu-highlight.css">

        <!-- Custom theme stylesheets -->
        

        
    </head>
    <body>
        <!-- Provide site root to javascript -->
        <script type="text/javascript">
            var path_to_root = "";
            var default_theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "navy" : "rust";
        </script>

        <!-- Work around some values being stored in localStorage wrapped in quotes -->
        <script type="text/javascript">
            try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }
        </script>

        <!-- Set the theme before any content is loaded, prevents flash -->
        <script type="text/javascript">
            var theme;
            try { theme = localStorage.getItem('mdbook-theme'); } catch(e) { }
            if (theme === null || theme === undefined) { theme = default_theme; }
            var html = document.querySelector('html');
            html.classList.remove('no-js')
            html.classList.remove('rust')
            html.classList.add(theme);
            html.classList.add('js');
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script type="text/javascript">
            var html = document.querySelector('html');
            var sidebar = 'hidden';
            if (document.body.clientWidth >= 1080) {
                try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch(e) { }
                sidebar = sidebar || 'visible';
            }
            html.classList.remove('sidebar-visible');
            html.classList.add("sidebar-" + sidebar);
        </script>

        <nav id="sidebar" class="sidebar" aria-label="Table of contents">
            <div class="sidebar-scrollbox">
                <ol class="chapter"><li class="chapter-item expanded "><a href="raffiot.html"><strong aria-hidden="true">1.</strong> Robust and Fast Functional IO Toolkit</a></li><li class="chapter-item expanded "><a href="first_steps.html"><strong aria-hidden="true">2.</strong> First Steps with IO</a></li><li class="chapter-item expanded "><a href="failures.html" class="active"><strong aria-hidden="true">3.</strong> Failures</a></li><li class="chapter-item expanded "><a href="context.html"><strong aria-hidden="true">4.</strong> Context</a></li><li class="chapter-item expanded "><a href="lists.html"><strong aria-hidden="true">5.</strong> Combining a list of IOs</a></li><li class="chapter-item expanded "><a href="async.html"><strong aria-hidden="true">6.</strong> Concurrent Programming</a></li><li class="chapter-item expanded "><a href="resource.html"><strong aria-hidden="true">7.</strong> Resource Management</a></li></ol>
            </div>
            <div id="sidebar-resize-handle" class="sidebar-resize-handle"></div>
        </nav>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                
                <div id="menu-bar-hover-placeholder"></div>
                <div id="menu-bar" class="menu-bar sticky bordered">
                    <div class="left-buttons">
                        <button id="sidebar-toggle" class="icon-button" type="button" title="Toggle Table of Contents" aria-label="Toggle Table of Contents" aria-controls="sidebar">
                            <i class="fa fa-bars"></i>
                        </button>
                        <button id="theme-toggle" class="icon-button" type="button" title="Change theme" aria-label="Change theme" aria-haspopup="true" aria-expanded="false" aria-controls="theme-list">
                            <i class="fa fa-paint-brush"></i>
                        </button>
                        <ul id="theme-list" class="theme-popup" aria-label="Themes" role="menu">
                            <li role="none"><button role="menuitem" class="theme" id="light">Light</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="rust">Rust (default)</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="coal">Coal</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="navy">Navy</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="ayu">Ayu</button></li>
                        </ul>
                        
                        <button id="search-toggle" class="icon-button" type="button" title="Search. (Shortkey: s)" aria-label="Toggle Searchbar" aria-expanded="false" aria-keyshortcuts="S" aria-controls="searchbar">
                            <i class="fa fa-search"></i>
                        </button>
                        
                    </div>

                    <h1 class="menu-title">RAFFIOT Guide</h1>

                    <div class="right-buttons">
                        
                        <a href="print.html" title="Print this book" aria-label="Print this book">
                            <i id="print-button" class="fa fa-print"></i>
                        </a>
                        
                        
                    </div>
                </div>

                
                <div id="search-wrapper" class="hidden">
                    <form id="searchbar-outer" class="searchbar-outer">
                        <input type="search" name="search" id="searchbar" name="searchbar" placeholder="Search this book ..." aria-controls="searchresults-outer" aria-describedby="searchresults-header">
                    </form>
                    <div id="searchresults-outer" class="searchresults-outer hidden">
                        <div id="searchresults-header" class="searchresults-header"></div>
                        <ul id="searchresults">
                        </ul>
                    </div>
                </div>
                

                <!-- Apply ARIA attributes after the sidebar and the sidebar toggle button are added to the DOM -->
                <script type="text/javascript">
                    document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                    document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                    Array.from(document.querySelectorAll('#sidebar a')).forEach(function(link) {
                        link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                    });
                </script>

                <div id="content" class="content">
                    <main>
                        <h1 id="failures"><a class="header" href="#failures">Failures</a></h1>
<p>All the computation we have seen until now were successful.
We will now see how <code>IO</code>'s failure management works.
But before, I need to present you the <code>Result[E,A]</code> type.</p>
<h2 id="the-resultea-type"><a class="header" href="#the-resultea-type">The <code>Result[E,A]</code> type</a></h2>
<p><code>Result[E,A]</code> represent the result of a computation.
A computation can either be successful, returning a value of type <code>A</code>,
or failed with an expected error of type <code>E</code>, or failed with an
unexpected exception.
<code>IO</code> and <code>Result</code> make a distinction between expected failures,
called <em>errors</em>, and unexpected failures, called <em>panics</em>.</p>
<p>For an operating system, an application crashing is an expected error.
A well designed operating system is expected to be prepared to such
errors. It has to deal with situations like this nicely and continue
running normally. Errors are part of the normal life of your program.
An error means that some operation failed but your program is still
healthy.</p>
<p>On the contrary, memory corruption inside the kernel is an unexpected
error. The system can not continue running normally. The failure may
have made the computation dangerous and/or the result wrong. The only
option is terminating the system as smoothly as possible.
Panics should never happen, but sometimes even the most improbable events
do occur. When panics happen, consider your computation lost. Terminate
it doing as little damage as possible.</p>
<p>For the rest of this section, you will need these imports.</p>
<pre><code class="language-python">&gt;&gt;&gt; from raffiot import result
&gt;&gt;&gt; from raffiot.result import Result, Ok, Error, Panic
</code></pre>
<h3 id="oksuccessa--a-success"><a class="header" href="#oksuccessa--a-success"><code>Ok(success:A)</code> : A Success</a></h3>
<p>When a computation successfully return some value <code>a</code> of type <code>A</code>,
it actually returns the value <code>Ok(a)</code> of type <code>Result[E,A]</code>. The
value <code>a</code> can be obtained by <code>Ok(a).success</code>:</p>
<pre><code class="language-python">&gt;&gt;&gt; result : Result[Any,int] = Ok(5)
&gt;&gt;&gt; result
Ok(success=5)
&gt;&gt;&gt; result.success
5
</code></pre>
<h3 id="errorerrore--an-expected-failure"><a class="header" href="#errorerrore--an-expected-failure"><code>Error(error:E)</code> : An Expected Failure</a></h3>
<p>When a computation fail because of an error <code>e</code> of type <code>E</code>,
it actually return a value <code>Error(e)</code> of type <code>Result[E,Any]</code>.
The type <code>E</code> can be any type you want. Choose as type <code>E</code> a type
that fit your business domain errors the best.
The error <code>e</code> can be obtained by <code>Error(e).error</code>:</p>
<pre><code class="language-python">&gt;&gt;&gt; result : Result[int,Any] = Error(5)
&gt;&gt;&gt; result
Error(error=5)
&gt;&gt;&gt; result.error
5
</code></pre>
<h3 id="panicexceptionexception--an-unexpected-failure"><a class="header" href="#panicexceptionexception--an-unexpected-failure"><code>Panic(exception:Exception)</code> : An Unexpected Failure</a></h3>
<p>When a computation fail because of an unexpected failure,
it actually return a value <code>Panic(p)</code> of type <code>Result[Any,Any]</code>
where <code>p</code> is the exception encountered.
The exception type is always the Python exception type <code>Exception</code>.
The exception <code>p</code> can be obtained by <code>Panic(p).exception</code>:</p>
<pre><code class="language-python">&gt;&gt;&gt; result : Result[Any,Any] = Panic(Exception(&quot;BOOM!&quot;))
&gt;&gt;&gt; result
Panic(exception=Exception('BOOM!'))
&gt;&gt;&gt; result.exception
Exception('BOOM!')
</code></pre>
<h3 id="fold--transforming-a-resultea"><a class="header" href="#fold--transforming-a-resultea"><code>fold</code> : transforming a <code>Result[E,A]</code></a></h3>
<p>To transform a <code>Result[E,A]</code>, use the method <code>fold</code>. It takes
as argument three functions. The first one is called when the
result is an <code>Ok</code>. The second is called when it is an <code>Error</code>.
The third is called when it is a <code>Panic</code>. When called, each of
these function receive as argument the value/error/exception
(depending on the case) stored in the result:</p>
<pre><code class="language-python">&gt;&gt;&gt; Ok(5).fold(
...   lambda s: f&quot;success: {s}&quot;,
...   lambda e: f&quot;error: {e}&quot;,
...   lambda p: f&quot;exeption: {p}&quot;
... )
'success: 5'
&gt;&gt;&gt; Error(7).fold(
...   lambda s: f&quot;success: {s}&quot;,
...   lambda e: f&quot;error: {e}&quot;,
...   lambda p: f&quot;exeption: {p}&quot;
... )
'error: 7'
&gt;&gt;&gt; Panic(Exception(&quot;BOOM!&quot;)).fold(
...   lambda s: f&quot;success: {s}&quot;,
...   lambda e: f&quot;error: {e}&quot;,
...   lambda p: f&quot;exeption: {p}&quot;
... 
'exeption: BOOM!'
</code></pre>
<h3 id="raise_on_panic--reporting-panics-as-exceptions"><a class="header" href="#raise_on_panic--reporting-panics-as-exceptions"><code>raise_on_panic</code> : reporting panics as exceptions</a></h3>
<p><em>Raffiot</em>'s functions and methods never raise exception
but instead return a <code>Panic</code>. When you need a failed
computation to raise the exception, call <code>raise_on_panic</code>
on the result:</p>
<pre><code class="language-python">&gt;&gt;&gt; Ok(5).raise_on_panic()
Ok(success=5)
&gt;&gt;&gt; Error(7).raise_on_panic()
Error(error=7)
&gt;&gt;&gt; Panic(Exception(&quot;BOOM!&quot;)).raise_on_panic()
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/tof/dev/raffiot.py/raffiot/result.py&quot;, line 406, in raise_on_panic
    raise self.exception
Exception: BOOM!
</code></pre>
<p><code>raise_on_panic</code> is <strong>the only function/method raising exceptions</strong>.
Never expect other functions to raise exception on failures, they
will return an <code>Error</code> or <code>Panic</code> instead:</p>
<pre><code class="language-python">&gt;&gt;&gt; main : IO[None,None,None] = io.panic(Exception(&quot;BOOM!&quot;))
&gt;&gt;&gt; main.run(None)
Panic(exception=Exception('BOOM!'))
&gt;&gt;&gt; main.run(None).raise_on_panic()
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/tof/dev/raffiot.py/raffiot/result.py&quot;, line 406, in raise_on_panic
    raise self.exception
Exception: BOOM!
</code></pre>
<h2 id="errors-expected-failures-in-io"><a class="header" href="#errors-expected-failures-in-io">Errors: Expected failures in IO</a></h2>
<p><code>IO</code> has built-in support errors. Remember that we call error the
expected failures. Errors can be of any type you want. You should
usually take as error type the one that fit your business domain
errors the best. <strong>In the type <code>IO[R,E,A]</code>, <code>E</code> is the type of errors</strong>.</p>
<h3 id="error--this-failure-was-expected-were-still-in-safe-zone"><a class="header" href="#error--this-failure-was-expected-were-still-in-safe-zone"><code>error</code> : this failure was expected, we're still in safe zone!</a></h3>
<p>To raise an error, simply call <code>io.error</code>:</p>
<pre><code class="language-python">&gt;&gt;&gt; from typing import Any, List

&gt;&gt;&gt; main_str : IO[None,str,Any] = io.error(&quot;Oops&quot;)
&gt;&gt;&gt; main_str.run(None)
Error(error='Oops')

&gt;&gt;&gt; main_int : IO[None,int,Any] = io.error(5)
&gt;&gt;&gt; main_int.run(None)
Error(error=5)

&gt;&gt;&gt; main_list : IO[None,List[int],Any] = io.error([1,2,3])
&gt;&gt;&gt; main_list.run(None)
Error(error=[1, 2, 3])
</code></pre>
<h3 id="catch--reacting-to-expected-failures-to-continue"><a class="header" href="#catch--reacting-to-expected-failures-to-continue"><code>catch</code> : reacting to expected failures to continue.</a></h3>
<p>To react to errors, just call the method <code>catch</code>.
It is very similar to a <code>try-exept</code> block.
It takes as argument a function called the <em>error handler</em>.
When the computation fails because of an error <code>e</code>,
the error handler is called with <code>e</code> as argument.
The result is then the error handler's result.</p>
<pre><code class="language-python">&gt;&gt;&gt; def main(i: int) -&gt; IO[None,str,int]:
...   return (
...   io.error(i)
...   .catch(lambda x:
...     io.pure(2*x)
...     if x % 2 == 0
...     else io.error(&quot;Oops&quot;))
... )
&gt;&gt;&gt; main(5).run(None)
Error(error='Oops')
&gt;&gt;&gt; main(6).run(None)
Ok(success=12)
</code></pre>
<p>If the computation is successful, or if it failed on a panic,
then <code>catch</code> has no effect.
Note that the error handler can itself raise errors and panics.</p>
<h3 id="map_error--transforming-expected-failures"><a class="header" href="#map_error--transforming-expected-failures"><code>map_error</code> : transforming expected failures.</a></h3>
<p>It is often useful to transform an error. For example you may
want to add some useful information about the context: what
was the request that led to this error, what were the arguments
of the operation that failed, etc.</p>
<p>To transform an error, call <code>map_error</code>. It behaves like <code>map</code>,
but on errors:</p>
<pre><code class="language-python">&gt;&gt;&gt; main : IO[None,int,Any] = io.error([1,2]).map_error(lambda l: l[0] + l[1])
&gt;&gt;&gt; main.run(None)
Error(error=3)
</code></pre>
<p>If the computation is successful or if it fails on a panic,
then <code>map_error</code> has no effect.</p>
<h2 id="panics-unexpected-failures-in-io"><a class="header" href="#panics-unexpected-failures-in-io">Panics: Unexpected Failures in IO</a></h2>
<p>The type of panics is always the Python type of exception <code>Exception</code>.
Panics can be raise either manually, by calling <code>io.panic</code>, or
when <code>run</code> encounters an exception.
<strong>The method <code>run</code> on <code>IO</code> never raises exceptions!</strong>
Every exception <code>p</code> raised during the execution of <code>run</code> are caught and
transformed into panics <code>Panic(p)</code>.</p>
<h3 id="all-exceptions-are-caught"><a class="header" href="#all-exceptions-are-caught"><strong>ALL</strong> exceptions are caught</a></h3>
<p>All the functions and method that accept functions as arguments
run them inside a <code>try-except</code> block to catch every raised exception.
All exception caught this way are transformed into panics:</p>
<pre><code class="language-python">&gt;&gt;&gt; main : IO[None,None,float] = io.pure(0).map(lambda x: 1/x)
&gt;&gt;&gt; main.run(None)
Panic(exception=ZeroDivisionError('division by zero'))
</code></pre>
<p>Remember that panics are unexpected failures and unexpected failures
should never happen. In an ideal world you should never give to
<code>map</code>, <code>flat_map</code>, <code>defer</code> and others functions that may raise exceptions.
In an ideal world, panics would never occur. But we do not live in an
ideal world, so <code>map</code>, <code>flat_map</code> and others covers your back by
catching any exception for your own safety.</p>
<h3 id="panic--something-went-terribly-wrong-were-in-unsafe-zone"><a class="header" href="#panic--something-went-terribly-wrong-were-in-unsafe-zone"><code>panic</code> : something went terribly wrong, we're in <strong>unsafe</strong> zone.</a></h3>
<p>It is sometimes useful to manually raise panics. For example when
you encounter a problematic situation you though were impossible
but still did happen. If your program is not designed to handle this
situation, you should raise a panic.</p>
<pre><code class="language-python">&gt;&gt;&gt; main : IO[None,None,Any] = io.panic(Exception(&quot;BOOM!&quot;))
&gt;&gt;&gt; main.run(None)
Panic(exception=Exception('BOOM!'))
</code></pre>
<h3 id="recover--stopping-the-computation-safely-after-an-unexpected-failure"><a class="header" href="#recover--stopping-the-computation-safely-after-an-unexpected-failure"><code>recover</code> : <strong>stopping</strong> the computation safely after an unexpected failure.</a></h3>
<p>Even in case of a panic, you have a chance to perform some emergency
actions to recover. For example, you may want to restart the computation
on panics. To react to panics, just call <code>recover</code>.
It is very similar to a <code>try-exept</code> block.
It takes as argument a function, called the <em>panic handler</em>.
If the computation fails because of a panic <code>p</code>, then the panic handler
is called with <code>p</code> as argument.
The result is then the the handler's result.</p>
<pre><code class="language-python">&gt;&gt;&gt; main : IO[None,None,Any] = (
...   io.panic(Exception(&quot;BOOM!&quot;))
...   .recover(lambda p: io.pure(&quot;Recovered from &quot; + str(p)))
... )
&gt;&gt;&gt; main.run(None)
Ok(success='Recovered from BOOM!')
</code></pre>
<h3 id="map_panic--transforming-an-unexpected-failure"><a class="header" href="#map_panic--transforming-an-unexpected-failure"><code>map_panic</code> : transforming an unexpected failure.</a></h3>
<p>It is often useful to transform a panic. For example you may
want to add some useful information about the context: what
was the request that led to this error, what were the arguments
of the operation that failed, etc.</p>
<p>To transform an error, call <code>map_panic</code>. It behaves like <code>map</code>,
but on panics:</p>
<pre><code class="language-python">&gt;&gt;&gt; main : IO[None, None, None] = (
...   io.pure(0)
...   .map(lambda x: 1/x)
...   .map_panic(lambda exception: Exception(&quot;BOOM&quot;))
... )
&gt;&gt;&gt; main.run(None)
Panic(exception=Exception('BOOM'))
</code></pre>
<h3 id="more-tools"><a class="header" href="#more-tools">More tools</a></h3>
<p>Here are some very useful functions. They can all be expressed using the
functions and methods seen above but they deserve being seeing in details:</p>
<h3 id="attempt--failures-as-values"><a class="header" href="#attempt--failures-as-values"><code>attempt</code> : failures as values.</a></h3>
<p>The method <code>attemp</code> transform an <code>IO[R,E,A]</code> into
<code>IO[R,None,Result[E,A]]</code>. If the original computation is successful,
the transformed one returns an <code>Ok</code>. If the original computation fails
on an error <code>e</code>, the transformed one returns <code>Error(e)</code>. If the original
computation fails on a panic <code>p</code>, the transformed one returns <code>Panic(p)</code>:</p>
<pre><code class="language-python">&gt;&gt;&gt; io_ok : IO[None,None,Result[None,int]] = io.pure(5).attempt()
&gt;&gt;&gt; io_ok.run(None)
Ok(success=Ok(success=5))
&gt;&gt;&gt; io_error : IO[None,None,Result[int,None]] = io.error(7).attempt()
&gt;&gt;&gt; io_error.run(None)
Ok(success=Error(error=7))
&gt;&gt;&gt; io_panic : IO[None,None,Result[None,None]] = io.panic(Exception(&quot;BOOM!&quot;)).attempt()
&gt;&gt;&gt; io_panic.run(None)
Ok(success=Panic(exception=Exception('BOOM!')))
</code></pre>
<p>It is hugely useful when you want to do different actions depending
on the result of a computation. Calling <code>attempt</code> and <code>flat_map</code> is
easier than combining <code>flat_map</code>, <code>catch</code> and <code>recover</code> correctly.</p>
<h3 id="from_result--from-resultea-to-iononeea"><a class="header" href="#from_result--from-resultea-to-iononeea"><code>from_result</code> : from <code>Result[E,A]</code> to <code>IO[None,E,A]</code></a></h3>
<p>The function <code>io.from_result</code> does almost the opposite of <code>attempt</code>.
It transform a <code>Result[E,A]</code> into the corresponding <code>IO[None,E,A]</code>:</p>
<pre><code class="language-python">&gt;&gt;&gt; io_ok : IO[None,None,int] = io.from_result(Ok(5))
&gt;&gt;&gt; io_ok.run(None)
&gt;&gt;&gt; io_error : IO[None,int,None] = io.from_result(Error(5))
&gt;&gt;&gt; io_error.run(None)
Error(error=5)
&gt;&gt;&gt; io_panic : IO[None,None,None] = io.from_result(Panic(Exception(&quot;BOOM!&quot;)))
&gt;&gt;&gt; io_panic.run(None)
Panic(exception=Exception('BOOM!'))
</code></pre>
<p><code>from_result</code> is often useful after an <code>attempt</code> to restore the state
of the computation.</p>
<h3 id="finally_--doing-something-unconditionally"><a class="header" href="#finally_--doing-something-unconditionally"><code>finally_</code> : doing something unconditionally.</a></h3>
<p>The method <code>finally_</code> is the <em>finally</em> clause of a <em>try-except-finally</em>.
It executed an <code>IO</code> after the current one, discard its result and
restore the result of the current one:</p>
<pre><code class="language-python">&gt;&gt;&gt; pure(5).finally_(io.defer(print, &quot;Hello&quot;)).run(None)
Hello
Ok(success=5)
&gt;&gt;&gt; error(7).finally_(io.defer(print, &quot;Hello&quot;)).run(None)
Hello
Error(error=7)
&gt;&gt;&gt; panic(Exception(&quot;BOOM!&quot;)).finally_(io.defer(print, &quot;Hello&quot;)).run(None)
Hello
Panic(exception=Exception('BOOM!'))
</code></pre>
<h3 id="on_failure--reaction-to-both-errors-and-panics"><a class="header" href="#on_failure--reaction-to-both-errors-and-panics"><code>on_failure</code> : reaction to both errors and panics.</a></h3>
<p>Calling both methods <code>catch</code> and <code>recover</code> is sometimes annoying.
When you need to react to any failure, call <code>on_failure</code>. It
takes as argument a function called the <em>failure handler</em>.
When a computation fails, it calls the failure handler with the
failure passed as argument as a <code>Result[E,None]</code>.</p>
<p>This <code>Result[E,None]</code> is never <code>Ok</code> because <code>on_failure</code> call the handler
only on failures.</p>
<pre><code class="language-python">&gt;&gt;&gt; pure(5).on_failure(lambda x: pure(12)).run(None)
Ok(success=5)
&gt;&gt;&gt; error(7).on_failure(lambda x: pure(12)).run(None)
Ok(success=12)
&gt;&gt;&gt; panic(Exception(&quot;BOOM!&quot;)).on_failure(lambda x: pure(12)).run(None)
Ok(success=12)
</code></pre>

                    </main>

                    <nav class="nav-wrapper" aria-label="Page navigation">
                        <!-- Mobile navigation buttons -->
                        
                            <a rel="prev" href="first_steps.html" class="mobile-nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        

                        
                            <a rel="next" href="context.html" class="mobile-nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        

                        <div style="clear: both"></div>
                    </nav>
                </div>
            </div>

            <nav class="nav-wide-wrapper" aria-label="Page navigation">
                
                    <a rel="prev" href="first_steps.html" class="nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                        <i class="fa fa-angle-left"></i>
                    </a>
                

                
                    <a rel="next" href="context.html" class="nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                        <i class="fa fa-angle-right"></i>
                    </a>
                
            </nav>

        </div>

        

        

        

        
        <script type="text/javascript">
            window.playground_copyable = true;
        </script>
        

        

        
        <script src="elasticlunr.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="mark.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="searcher.js" type="text/javascript" charset="utf-8"></script>
        

        <script src="clipboard.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="highlight.js" type="text/javascript" charset="utf-8"></script>
        <script src="book.js" type="text/javascript" charset="utf-8"></script>

        <!-- Custom JS scripts -->
        

        

    </body>
</html>
